# Generated by Django 6.0.4 on 2026-04-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='howard',
            field=models.BooleanField(default=False),
        ),
    ]
