# Generated by Django 6.0.4 on 2026-04-29 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_question_howard'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameboard',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
    ]
