# Generated by Django 6.0.4 on 2026-05-05 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_gameboard_date_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='gameboard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='quickstart.gameboard'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE quickstart_leaderboardentry "
                        "ALTER COLUMN time_taken TYPE integer "
                        "USING EXTRACT(EPOCH FROM time_taken)::integer"
                    ),
                    reverse_sql=(
                        "ALTER TABLE quickstart_leaderboardentry "
                        "ALTER COLUMN time_taken TYPE interval "
                        "USING make_interval(secs => time_taken)"
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='leaderboardentry',
                    name='time_taken',
                    field=models.IntegerField(),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='gameboards',
            field=models.ManyToManyField(related_name='questions', to='quickstart.gameboard'),
        ),
    ]
