# Generated by Django 6.0.4 on 2026-05-05 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_delete_user_alter_leaderboard_gameboard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardentry',
            name='leaderboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='quickstart.leaderboard'),
        ),
    ]
