# Generated by Django 6.0.5 on 2026-05-06 03:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_alter_leaderboardentry_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameboard',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
